// svelte/src/components/Board.svelte
<script>
  /** @typedef {import('../../../shared/mockData').ColumnData} ColumnData */
  /** @typedef {import('../../../shared/mockData').CardData} CardData */
  import Column from './Column.svelte';

  /**
   * @type {{
   *   columns: ColumnData[],
   *   onDragStart: (e: DragEvent, cardId: string) => void,
   *   onDrop: (columnId: string) => void
   * }}
   */
  let { columns, onDragStart, onDrop } = $props();
</script>

<div class="board-grid">
  {#each columns as column (column.id)}
    <Column
      {column}
      cards={column.cards}
      {onDragStart}
      {onDrop}
    />
  {/each}
</div>

// solidjs/src/components/Board.jsx
/** @jsxImportSource solid-js */
import { For } from "solid-js";
import { Column } from "./Column";

export const Board = (props) => {
  return (
    <div class="board-grid">
      <For each={props.columns}>
        {(column) => (
          <Column
            column={column}
            cards={column.cards}
            onDragStart={props.onDragStart}
            onDrop={props.onDrop}
          />
        )}
      </For>
    </div>
  );
};
