// solidjs/src/components/Board.jsx
/** @jsxImportSource solid-js */
import { For } from "solid-js";
import { Column } from "./Column";

export const Board = (props) => {
  return (
    <div class="board-grid">
      <For each={props.columns}>
        {(column) => (
          <Column
            column={column}
            cards={column.cards}
            onDragStart={props.onDragStart}
            onDrop={props.onDrop}
          />
        )}
      </For>
    </div>
  );
};

// react/src/components/Board.jsx
import { Column } from "./Column";

export const Board = ({ columns, onDragStart, onDrop }) => {
  return (
    <div className="board-grid">
      {columns.map((column) => (
        <Column
          key={column.id}
          column={column}
          cards={column.cards}
          onDragStart={onDragStart}
          onDrop={onDrop}
        />
      ))}
    </div>
  );
};
