// svelte/src/components/Column.svelte
<script>
  /** @jsxImportSource svelte */
  import Card from './Card.svelte';

  let { column, cards, onDragStart, onDrop } = $props();

  function handleDragOver(e) {
    e.preventDefault();
  }
</script>

<div
  class="column"
  ondragover={handleDragOver}
  ondrop={() => onDrop(column.id)}
>
  <div class="column-header">
    <span>{column.title}</span>
    <span class="card-count">{cards.length}</span>
  </div>
  <div class="card-list">
    {#each cards as card (card.id)}
      <Card {card} {onDragStart} />
    {/each}
  </div>
</div>

// react/src/components/Column.jsx
import { Card } from "./Card";

export const Column = ({ column, cards, onDragStart, onDrop }) => {
  const handleDragOver = (e) => {
    e.preventDefault();
  };

  return (
    <div
      className="column"
      onDragOver={handleDragOver}
      onDrop={() => onDrop(column.id)}
    >
      <div className="column-header">
        <span>{column.title}</span>
        <span className="card-count">{cards.length}</span>
      </div>
      <div className="card-list">
        {cards.map((card) => (
          <Card key={card.id} card={card} onDragStart={onDragStart} />
        ))}
      </div>
    </div>
  );
};
