// solidjs/src/components/Column.jsx
/** @jsxImportSource solid-js */
import { For } from "solid-js";
import { Card } from "./Card";

export const Column = (props) => {
  const handleDragOver = (e) => {
    e.preventDefault();
  };

  return (
    <div
      class="column"
      ondragover={handleDragOver}
      ondrop={() => props.onDrop(props.column.id)}
    >
      <div class="column-header">
        <span>{props.column.title}</span>
        <span class="card-count">{props.cards.length}</span>
      </div>
      <div class="card-list">
        <For each={props.cards}>
          {(card) => <Card card={card} onDragStart={props.onDragStart} />}
        </For>
      </div>
    </div>
  );
};

// svelte/src/components/Column.svelte
<script>
  /** @jsxImportSource svelte */
  import Card from './Card.svelte';

  let { column, cards, onDragStart, onDrop } = $props();

  function handleDragOver(e) {
    e.preventDefault();
  }
</script>

<div
  class="column"
  ondragover={handleDragOver}
  ondrop={() => onDrop(column.id)}
>
  <div class="column-header">
    <span>{column.title}</span>
    <span class="card-count">{cards.length}</span>
  </div>
  <div class="card-list">
    {#each cards as card (card.id)}
      <Card {card} {onDragStart} />
    {/each}
  </div>
</div>
